deepmodeling/dpgen

generator/lib/gaussian.py
generator/tests/param-pyridine-gaussian.json
generator/tests/test_make_fp.py

- support keywords for multiple steps, e.g. `'keywords': ['mn15/6-31g** stable=opt nosymm scf(maxcyc=512)', 'mn15/6-31g** force nosymm scf(maxcyc=512) geom=chk guess=read']`
- support setting spin multiplicity automatically for `'multiplicity': 'auto'` by detecting connectivity

update Gaussian lib

---

README.md
dpgen/dispatcher/Batch.py
examples/run/dp-lammps-vasp/Al/param_al_all_gpu-deepmd-kit-1.1.0.json
examples/run/dp-lammps-vasp/CH4/param_CH4_deepmd-kit-1.1.0.json
tests/dispatcher/shell/test_shell_local.py

add CH4 & Al param.json for deepmd-kit-1.1.0 ;modify doc

add CH4 & Al param.json for deepmd-kit-1.1.0 ;modify doc

---

dpgen/auto_test/lib/util.py

error：File "/data1/wanrunj/.conda/envs/python368/lib/python3.6/site-packages/dpgen/auto_test/lib/util.py", line 63, in make_work_path
task_type=task_type+'-reprod-k%.2f' % (kspacing)
UnboundLocalError: local variable 'kspacing' referenced before assignment
Adding missed assignment for “kspacing”  @amcadmus

bug_fix: test | deepmd | task 04.interstitial | "reprod_opt": 【true】

---

dpgen/dispatcher/Batch.py

The train_command has been replaced in the format { xxxxx }, so if there is not a ";" before it , there will be a bug.
Like
CUDA_VISIBLE_DEVICES=2  { if [ ! -f model.ckpt.index ]; then dp train input.json; else dp train input.json --restart model.ckpt; fi }  1>> train.log 2>> train.log  &

Fix bug if cuda_multi_tasks is used

---

README.md
dpgen/generator/lib/cp2k.py
tests/generator/param-pyridine-cp2k.json

The OT section is removed from default input, since "OT" and "diagonalization"  are required for semiconductor and metal, respectively. The users should select one of them based on their cases.  The rest of default input is reserved to ensure the correct print in the output which can be parsed by dpdata(like force information)

change the default input for cp2k

---

dpgen/dispatcher/Dispatcher.py

prevent dpgen crash when submitting jobs, especially when there are many jobs to submit or task_max is set, so dpgen can restart submitting then

dump job record after every submitting

---

dpgen/generator/run.py
tests/generator/test_make_md.py

Key `sys_rev_mat` is added to `model_devi_jobs` of `param.json` to support using different parameters for each system selected in `sys_idx` when using `rev_mat` generating Lammps input files, as well as Plumed input. Therefore, users could choose their parameters **according to the properties of initial structure** in exploring steps, in prevention of poor structures with extremely large model deviation.
Unit test is also added, respectively.
An example is shown below:
```json
"model_devi_jobs": [
{
"template":{"lmp": "lmp_tmp/input.lammps"},
"sys_idx": [0, 1],
"traj_freq": 50,
"rev_mat":{
"lmp": {
"V_NSTEPS": [50000],
"V_TEMP": [100, 200, 300, 400, 500, 600, 700]
}
},
"sys_rev_mat": {
"0": {"lmp": {"V_DIS": [1.3, 1.6, 1.8], "V_FORCE": [80.0]}},
"1": {"lmp": {"V_DIS": [3.0, 4.0, 5.0], …
```

Allow using different parameters for each sys_idx in model deviation

---

dpgen/auto_test/Lammps.py

adding the parameter for "type_map" when using dpdata to convert config from 'POSCAR' to 'conf.lmp'. related function " lammps.cvt_lammps_conf" is defined in /lib/lammps.py

Update Lammps.py: using "type_map" when evoking dpdata

---

dpgen/dispatcher/LSF.py

For there is an `exclude_list` for Slurm and the very function could be useful in this PR I include the function for LSF system. With the function, users could exclude some hosts when submitting to their remote cluster in prevention of bad hosts.

add exclude list for LSF

---

dpgen/auto_test/lib/lammps.py

adding the parameter named "type_map_list" for "type_map" when using dpdata to covert config formats

using "type_map" when evoking dpdata | vasp/lammps

---

dpgen/dispatcher/LSF.py

A fix for #337 that include the missing quotes for `#BSUB -R` command, which may cause failure in submitting.

Add missing quotes for BSUB command (Fix for #337)

---

dpgen/generator/run.py

Revising the default value of training_reuse_old_ratio form "0.2" into "None".
Adding and error message with simple explanations and suggestions.

user-defined training_reuse_old_ratio is mandatory

---

dpgen/generator/run.py

RuntimeError message when training_reuse_old_ratio not found:
A recommended strategy is making the old-to-new ratio close to 10 times of the default value
--->
A recommended strategy is making the【new-to-old】ratio close to 10 times of the default value

fix_bug typo in RuntimeError message

---

dpgen/auto_test/Lammps.py

error when:
autotest converting lammps/dump containing N elements, when N < len(type_map)
caused by:
assert( len(data['atom_names'])==len(data['atom_numbs']) )
<-- len(data['atom_names']) = len(type_map), len(data['atom_numbs'] = 【len(type_list_set)】
<--【type_list_set = set(type_list), type_list is a list of lammps's atom_type in lammps/dump】
consquence:
can't conduct | dpgen autotest post | relaxation |, when N < len(type_map):
Traceback (most recent call last):
File "/root/anaconda3/envs/autotest/bin/dpgen", line 8, in <module>
sys.exit(main())
File "/root/anaconda3/envs/autotest/lib/python3.7/site-packages/dpgen/main.py", line 175, in main
args.func(args)
File "/root/anaconda3/envs/autotest/lib/python3.7/site-packages/dpgen/auto_test/run.py", line 57, in gen_test
run_task(args.TASK, …

fix_bug Lammps.py

---

dpgen/dispatcher/Slurm.py

In #346 , `job_name` for Slurm was added for a clean task list. However, the modification made the very key a necessary one, or `KeyError` would be raised. So here I fixed the very bug.

fix KeyError of "job_name" for Slurm

---

dpgen/auto_test/mpdb.py
dpgen/data/gen.py
dpgen/data/surf.py
dpgen/dispatcher/LSF.py
tests/auto_test/test_elastic.py
tests/auto_test/test_mpdb.py
tests/auto_test/test_surface.py
tests/auto_test/test_vacancy.py
tests/data/test_gen_bulk.py
tests/data/test_gen_surf.py
tests/data/test_gen_surf_poscar.py

Since last weekend, pymatgen released their v2022.0.* version, and as shown on official document, a backwards incompatible change has been introduced. I just followed the instruction official document to fix the incompatible issue for dpgen. Moreover, I checked the history code showing that the fix is supported since v2017.6.24.
Also, a typo error in LSF dispatcher was fixed.

fix pymatgen v2022.0.* incompatible issue (switch the branch)

---

dpgen/auto_test/Surface.py

wrong counting of the #atoms in both the surface structure and the equi structure, when computing the E per-atom of the corresponding two systems. 
was giving wrong surf-E for multi-component cases, and was giving "nan" if the number of atoms of the first elements is zero.
induced by using the  #atoms of the first elements as the total #atoms.

bug_fix | autotest | surf | post | multi-component systems

---

dpgen/dispatcher/SSHContext.py

This will fix the bug "gzip: 570aef2d-1f5f-4de3-b767-d5a2c4a8e41a.tar.gz already exists;  not overwritten" if dpgen stop and restart.

gzip with force overwrite

---

dpgen/dispatcher/SSHContext.py

open_sftp and close_sftp are expensive actions, especially when the
remote server is far away from the local server. This commit stores sftp
in the object and will reduce the frequency of open_sftp.
I have tested for several days and the speed has obviously increased.
cc @felix5572

store sftp and reduce frequency of open_sftp 

---

dpgen/generator/run.py

Fix BUG: only activation function in descriptor is updated if 1-dim `model_devi_activation_func` is provided

fix bug with 1-dim model_devi_activation_func

---

examples/run/dp1.x-lammps-cp2k/methane/param-ch4.json

A bug in DeePMD-kit v1.3.0 ~ v1.3.3 will ignore `n_neuron` (deepmodeling/deepmd-kit#846). Rename to prevent some one uses these versions.
@robinzyb

rename `n_neuron` to `neuron`

---

dpgen/data/gen.py

for INCAR param of VASP, NSW = 0 and 1 both lead to the output of 1 converged SCF, thus 1 valid frame of labeled data. 
NSW = 0 (actually single-point calculation) was not supported to be used as the "md_incar".
Though, the previous limitation might be reasonable in semantics, this update just support the practical branching in VASP settings and eliminates the annoying exception for users.

Update gen.py | compatibility with VASP

---

dpgen/data/gen.py

pert_numb = jdata['pert_numb'] 
stages 2 pert makes 000000+pert_numb structures (dirs),  pert_numb + 1 in total
stages 3 was copying those in range(pert_numb), the first  pert_numb structures(dir), lost the last one.

bug_fix | init_bulk | stages 3 | lost the last pert-dir in stages 2

---

dpgen/dispatcher/LocalContext.py

If the file to be downloaded is a softlink, `cp` should be performed instead of `mv`. Otherwise, `lfile` is still a file linked to some original file, and when this file's removed, `lfile` will be invalid.

Change mv to cp when downloading softlinks.

---

dpgen/generator/lib/lammps.py

The bare `pair_coeff` is not supported in the latest version of LAMMPS. `pair_coeff * *` should be used instead.
Fix deepmodeling/deepmd-kit#1201.

fix the usage of `pair_coeff`

---

dpgen/auto_test/common_equi.py
dpgen/auto_test/common_prop.py

If we rerun `dpgen autotest make param.json` and there are already task dirs in work directory, it only deletes and reproduces some input files like POSCAR,  but leaves behind result files in last run like OUTCAR.  Next when we run `dpgen autotest run param.json`, it will skip the task directories which already have the result files, and this may leads to a false data.
Change-Id: Ia138ee7c31b6c41d9f41f5943affa9ebf8803c46

autotest: rename task directory to avoid false result in a rerun

---

dpgen/data/gen.py

Now `skip_relax` is only checked in stage 2 (perturb and scale) and use an unrelaxed POSCAR.  It also should be checked in stage 1 to skip the relaxation job.
Change-Id: I12cc467e5956a5deb29ac4bd43719db1c0ef8942

init_bulk: skip relax if skip_relax is true

---

dpgen/dispatcher/SSHContext.py

In some case, FP calculations could read the wave function file or charge files (e.g., CHGCAR and WAVECAR in VASP ). If the size of those files is too big, the compress process could be very slow due to the default setting (compresslevel=9) in tarfile module of python. Change the compresslevel to 6 will accelate compress rate.

change compress level to 6 from default 9 to accelerate compress

---

README.md
dpgen/generator/run.py

Set `dp_compress` to `true` in parameters will enable model compression.
Fix #559.

support `dp compress`

---

dpgen/auto_test/EOS.py

currently, only count the #atoms of the first element when evaluating E-per-atom;

bug_fix | to support multi-element cases

---

dpgen/auto_test/VASP.py

if kspacing is provided in json,  will in fact use KSPACING=1 (default) to cal

bug_fix | typo in setting KSPACING

---

dpgen/generator/run.py

current behavior:
1）the list of models written in input.lammps for model_devi is created by "glob" without "sort" --> may give different (random) orders in different machine environments  --> would randomly alter the model being used to sample configurations (always use the first model written in imput.lammps)
---> could lead to unexpected performance, such as, when using together with "model_devi_activation_func" that allows four models to be nonequivalent.
2）when preparing input.lammps from iuser-provided template, the line begin with "pair_style deepmd" will be overwritten by dpgen, thus overwrites the user defined order of models ---> could lead to unexpected performance, such as, when using together with "model_devi_activation_func" that allows four models to be nonequivalent and …

model_devi | sort models in default&support user-defined order

---

dpgen/auto_test/Lammps.py
dpgen/data/gen.py
dpgen/data/reaction.py
dpgen/data/surf.py
dpgen/data/tools/cessp2force_lin.py
dpgen/database/run.py
dpgen/database/vasp.py
dpgen/dispatcher/ALI.py
dpgen/dispatcher/Dispatcher.py
dpgen/dispatcher/DispatcherList.py
dpgen/dispatcher/LSF.py
dpgen/dispatcher/SSHContext.py
dpgen/dispatcher/Shell.py
dpgen/dispatcher/Slurm.py
dpgen/generator/run.py
dpgen/remote/RemoteJob.py
dpgen/remote/decide_machine.py
dpgen/remote/group_jobs.py
dpgen/simplify/simplify.py
dpgen/tools/relabel.py
dpgen/tools/stat_iter.py
tests/auto_test/test_mpdb.py
tests/database/test_db_vasp.py
tests/dispatcher/shell/test_shell_ssh.py
tests/dispatcher/test_ssh_context.py

The latter will not catch `KeyboardInterrupt` and `SystemExit`. See https://stackoverflow.com/a/18982726/9567349.

batch replace 'except:' with 'except Exception:'

---

dpgen/auto_test/lib/lammps.py

See https://github.com/deepmodeling/dpgen/pull/567 and https://github.com/deepmodeling/dpgen/issues/697

Fix the usage of `pair_coeff` in `auto_test`

---

README.md
dpgen/generator/run.py
dpgen/simplify/simplify.py
dpgen/util.py

1. Used `dp model-devi` to calculate model deviation, instead of local calculation. Supported by deepmodeling/deepmd-kit#1618, released in v2.1.1. So the version earlier than 2.1.1 is not supported any more.
2. Assumed all systems are MultiSystems.
3. Removed energy model deviation support

refactor simplify

---

README.md
doc/run/example-of-machine.md
dpgen/remote/decide_machine.py
examples/machine/DeePMD-kit-1.x/machine-ali.json
examples/machine/DeePMD-kit-1.x/machine-lsf-slurm-cp2k.json
examples/machine/DeePMD-kit-1.x/machine-slurm-qe.json
examples/machine/DeePMD-kit-2.x/lebesgue_v2_machine.json
tests/tools/machine_fp_single2.json
tests/tools/test_convert_mdata.py

The mdata of a task is a list of a single dict. This "list" looks useless and not clear enough. So this commit supports using the dict without a list.
Note that old parameters are still supported, so no breaking changes are made. The "list" is just removed from all examples. Both list and non-list parameters are in the unit test.
Old parameter:
```
"train": [
{
"command": "dp"
}
]
```
New parameter:
```
"train": {
"command": "dp"
}
```

supports non-list mdata

---

dpgen/data/reaction.py
dpgen/data/surf.py
dpgen/dispatcher/Dispatcher.py

This commit upgrades init_reaction and init_surf to use dpdispatcher

upgrade all tasks to dpdispatcher

---

doc/toymodels/JiamengHuang_pr.md
dpgen/auto_test/EOS.py

update: add a new option of absolute volume in /dpgen/dpgen/auto_test/EOS.py

update: add a new option of absolute volume in /dpgen/dpgen/auto_test/EOS.py

---

dpgen/data/reaction.py

fix compatibility as the key was changed in the dpdispatcher

init_reaction: fix compatibility with new dpdispatcher

---

dpgen/dispatcher/DispatcherList.py
examples/machine/DeePMD-kit-1.0/machine-local-4GPU.json

In [issue#485](https://github.com/deepmodeling/dpgen/issues/485) the wrong spelling of 'failure' was found.

correct the wrong spelling of 'failure'

---

dpgen/generator/run.py

1. ratio_failed was not applied in post_fp_cp2k.
2. When a cp2k task fails, it returns an empty "output" file. Since dpdispatcher only checks whether the output file exists or not, it marks the task finished and sends back the empty file. An empty or not converged output file leads to errors in the following step. Commenting out check_type_map is a temporary solution, which can run the next step by ignoring empty output files. To solve this problem fundamentally, dpdispatcher should probably be modified as well. 
- add ratio_failed param to cp2k in 02.fp step
- fix a bug in `post_fp_cp2k`

fix ‘post_fp_cp2k’, add param rfailed

---

doc/index.rst
doc/init/init-reaction-jdata.rst
doc/init/init-reaction.md
dpgen/data/arginfo.py
dpgen/data/reaction.py
dpgen/util.py
examples/init/reaction.json
tests/test_check_examples.py

The commit includes:
- add docs
- add detailed arguments
- add strict argument checking
- strict check the init-reaction example

add init-reaction docs and args

---

dpgen/simplify/simplify.py

Since DP-GEN always deal with Systems (instead of LabeledSystems) here,  labeled should be set as False

for sys_entire, set labeled=False

---

dpgen/generator/run.py

When tcount == 0, 'ZeroDivisionError: float division by zero' is raised. Here the bug is fixed.

fix ZeroDivisionError raised by run.py

---

dpgen/generator/arginfo.py

The way to organize fp style variants is incorrect before.

fix fp style variants

---

doc/index.rst
doc/simplify/simplify-jdata.rst
dpgen/generator/arginfo.py
dpgen/simplify/arginfo.py
examples/simplify/qm7.json
tests/test_check_examples.py

add simplify jdata docs; fix and check example

---

README.md
doc/run/example-of-param.md
dpgen/generator/ch4/param.json
examples/run/deprecated/dp0.12-lammps-cp2k/CH4/param_CH4.json
examples/run/deprecated/param-h2oscan-vasp.json
examples/run/deprecated/param-mg-vasp-ucloud.json
examples/run/deprecated/param-mg-vasp.json
examples/run/deprecated/param-pyridine-pwscf.json
examples/run/dp1.x_lammps_gaussian/dodecane/dodecane.json
examples/simplify/qm7.json
tests/generator/param-mg-vasp-diy.json
tests/generator/param-mg-vasp-old.json
tests/generator/param-mg-vasp.json
tests/generator/param-mgo-cp2k-exinput.json
tests/generator/param-pyridine-cp2k.json
tests/generator/param-pyridine-gaussian.json
tests/generator/param-pyridine-pwmat.json
tests/generator/param-pyridine-pwscf-old.json
tests/generator/param-pyridine-pwscf.json
tests/generator/param-pyridine-siesta.json

remove `train_param` from examples, which was deprecated in #68

---

dpgen/generator/run.py
dpgen/simplify/simplify.py

When `job.json` is empty, it won't be generated. But post_fp_vasp will call it without checking if it exists. see [https://github.com/deepmodeling/dpgen/issues/794](issue #794)
Besides, there's something wrong with naming task directories. dpdata has to append all different systems into one set, which causes `RuntimeError('systems with inconsistent formula could not be append: %s v.s. %s' % (self.uniq_formula, system.uniq_formula))`. Now those problems are fixed.

fix post_fp_vasp and make_fp_configs for simplify

---

README.md
dpgen/generator/ch4/param.json
examples/run/dp-lammps-enhance_sampling/param.json
examples/simplify/qm7.json

- correct the wrong spelling of "perturb" and "perturbation" in `README.md`
- remove "load_ckpt", see #813

Fix readme and qm7.json

---

dpgen/generator/arginfo.py

The arguments #786 added should be optional.

args: trust level for model_devi_job should be optional

---

dpgen/simplify/simplify.py

If `type_map` is not set as PARAM, dpdata will change the order of elements, which causes `KeyError`. Here the bug is fixed.

set type_map for MultiSystems in model_devi step for simplify

---

dpgen/generator/arginfo.py

args: add entire training parameters

---

dpgen/generator/arginfo.py

I don't notice it's duplicated in #829 but the unit test in #821 has thrown errors.

args: remove duplicated argument

---

dpgen/generator/run.py

I found a bug when running a real calculation: fp_params not found when generating forward files. The reason is that kspacing can only found in fp_params, and I deleted the lines to get fp_params. This bug is fixed in this PR.

fix bug of not finding fp_params

---

README.md
dpgen/data/gen.py

Delete relax_kspacing and md_kspacing in abacus init step, because kspacing has been added in ABACUS itself. They have different unit (one in 1/Bohr and another in 1/A), and may cause confusions.

refactor: delete relax_kspacing and md_kspacing in abacus init step

---

README.md
dpgen/data/gen.py
dpgen/generator/lib/abacus_scf.py

Fix a bug in run_abacus_md and delete redundant line about gamma_only.

  Fix a bug in run_abacus_md and delete redundant line about gamma_only.

---

README.md

Change invalid command 'dpgen test' to 'dpgen autotest'.

Fix README: change 'dpgen test' to 'dpgen autotest'

---

doc/troubleshooting/common-errors.md

Add 3 error information ("dargs.dargs.ArgumentTypeError: [at root location] key `xxx` gets wrong value type, requires <xxx> but gets <xx>", "Dargs: xxx is not allowed in strict mode.","ValueError: Cannot load file containing picked data when allow_picked=False").
Since the last PR was directly changed in the devel branch, the PR was invalid after the fork repository was updated with the main repository, so it was resubmitted.
Signed-off-by: ziqi-hu <51811006+ziqi-hu@users.noreply.github.com>

docs: add 3 error information to common-errors.md

---

doc/index.rst
doc/simplify/simplify.md

Move the document from README to https://docs.deepmodeling.com/projects/dpgen/en/devel/

update simplify doucment

---

dpgen/auto_test/Elastic.py

equi_stress should have same unit as stress in elastic constant calculation.

fix: equi_stress should have the same unit as stress

---

dpgen/dispatcher/AWS.py
dpgen/generator/run.py

gromacswrapper throws lots of warnings. boto3 may cause critical errors. We move these imports into the runtime functions.
Fix #674.

move some imports into runtime functions

---

dpgen/data/surf.py

Support user use "forward_files" in machine parameters to upload other files besides POSCAR, INCAR, POTCAR. (forwarded files for each task)

Support forward files for init_surf

---

doc/init/init_surf.md

clarify the usage of skip_relax in init_surf

---

dpgen/generator/run.py

see #737 
dpdispatcher use flag_if_job_task_fail to mark the failed jobs, so `post_fp_check_fail` can be used before checking the frames. If we use the alternative way the issue mentioned, we should consider different representative outputs according to `fp_style`. I am wondering if it is a repeat of the following frame checks. However, since `flag_if_job_task_fail` will be marked as True if one task in the group is failed, I am afraid that `rfail` could be high when only a few tasks fail. I'd like to ask for some suggestions.

fix: check the number of collected data in `post_fp_check_fail`

---

dpgen/data/gen.py

- skip cell_type if from_poscar is True
- use from_poscar = jdata.get('from_poscar', False) to get from_poscar

fix: skip cell_type if from_poscar is True in init_bulk

---

dpgen/generator/run.py

`lmp_traj` should not be in `forward_files` in `run_model_devi` step.

fix: remove lmp_traj from forward_files in run_md_model_devi

---

dpgen/generator/run.py

Tested for both conditions when `model_devi_merge_traj` is true or false. To solve #938

fix: fix forward_files for merge_traj in run_md_model_devi

---

dpgen/generator/arginfo.py
dpgen/generator/run.py

Since there are lots of parameters still not added (#771, #773, #774, #781, #782), we only enable loose check for `dpgen run` (i.e. `strict_check=False`).

loose check dpgen run jdata

---

doc/run/overview-of-the-run-process.md
doc/user-guide/common-errors.md
doc/user-guide/troubleshooting.md
dpgen/dispatcher/LazyLocalContext.py
dpgen/dispatcher/LocalContext.py
dpgen/generator/arginfo.py
dpgen/generator/run.py
tests/dispatcher/test_local_context.py

Make some recently reported problems clear in code and documentation.

optimize document and error report based on FAQs

---

dpgen/generator/run.py

Fixes #970. It's not required for gaussian.

remove `_link_fp_vasp_pp` from `make_fp_gaussian`

---

dpgen/simplify/simplify.py

Since the simplify jdata is confirmed to be completed (if not, please remind me), we could enable the strict check.

strict check simplify jdata

---

doc/autotest/relaxation/index.rst

fix typo `Relaxation-get-started-and-input-examples`

fix : autotest relaxation TOC

---

doc/run/index.rst
doc/run/run-process.rst

merge run-process.rst to index.rst

---

.github/workflows/test.yml
.readthedocs.yaml
dpgen/auto_test/Interstitial.py
dpgen/auto_test/Vacancy.py
setup.py
tests/auto_test/test_interstitial.py
tests/auto_test/test_vacancy.py

Fix incompatibility of Interstitial.py and Vacancy.py with pymatgen>2022.7.9
add pymatgen-analysis-defect and pybind11 in setup.py.
add reminder for user to install pymatgen-analysis-defect if this package is not in their environment

Fix incompatibility of autotest module with latest pymatgen>2022.7.19

---

dpgen/generator/run.py

In ABACUS-DEEPKS, ABACUS need the deepks descriptor file when one of 'deepks_out_labels' and 'deepks_scf' is set to 1.

fix: modify the reading of parameter 'fp_dpks_descriptor' in run.py

---

dpgen/generator/lib/cp2k.py

python3.10 support: collection.Mapping -> collection.abc.Mapping
repair this: https://github.com/deepmodeling/dpgen/issues/1019

python3.10 support: collection.Mapping -> collection.abc.Mapping

---

doc/init/init_surf.md

Since "forward_files" for init_surf is supported (see #909), here add the relevant doc.

docs: init_surf forward_files

---

dpgen/auto_test/ABACUS.py
dpgen/generator/lib/abacus_scf.py
tests/auto_test/abacus_input/INPUT
tests/auto_test/equi/abacus/INPUT
tests/generator/abacus/INPUT.diy
tests/generator/param-methane-abacus.json
tests/generator/test_make_fp.py

The latest ABACUS 3.0.5 have removed the key word ·ntype·

Fix: remove the reading of `ntype` when treating ABACUS related info

---

.github/workflows/test.yml

The original implementation does not work. For example, see #1080.

fix pass action

---

dpgen/generator/run.py

Fix #1084. Both keys are valid, so we detect which one is used in `default_training_param`.

choose numb_steps/stop_batch automatically

---

dpgen/auto_test/common_equi.py
dpgen/auto_test/common_prop.py
dpgen/auto_test/lib/lammps.py
dpgen/data/gen.py
dpgen/generator/lib/lammps.py
dpgen/generator/lib/run_calypso.py
dpgen/generator/run.py
dpgen/remote/decide_machine.py
dpgen/simplify/simplify.py
pyproject.toml

`distutils` will be removed from Python 3.12. See [PEP 632](https://peps.python.org/pep-0632/).

replace distutils.version.LooseVersion by packaging.version.Version

---

doc/autotest/Auto-test.md

The type of parameter "structures" in `relaxation.json` of `dpgen autotest` should be a list. Fix the wrong type in Autotest Overview.

fix doc: "structures" should be a list

---

dpgen/generator/lib/utils.py
dpgen/simplify/simplify.py

Support "user_forward_files" for `simplify` in the `02.fp` step. Use abspath to create symlinks to avoid unexpected problems.

Support forward files for simplify

---

dpgen/data/gen.py
dpgen/data/surf.py

Replace "python3" in command by sys.executable

---

dpgen/simplify/simplify.py

**expected behavior**:
when `"labeled":true` in `dpgen simplify`, 02.fp will soft-link "labeled data", and the soft-linked "task dir" will also be created, for format consistency.
it is expected to be `data.000` and `task.000.000000`, 
being respectively guaranteed by funcs `data_system_fmt` and `fp_task_fmt`
**bug**:
the typo_bug used `data_system_fmt` for the "task dir" instead of `fp_task_fmt`,
then gives `task.000` instead of `task.000.000000`,
which makes `_check_empty_iter` (who checks `glob.glog("task.000.*")`) in `generator/run.py` sentence this iter empty,
then `00.train` of the next iter is always skipped.
**consequence**:
this make the "simplify_labeled" process never starts correctly, 
no iter0 model presents and randomly-picked data in iter0 are never trained, 
then iter1 …

fix_bug simplify.py

---

dpgen/generator/arginfo.py
dpgen/generator/run.py
dpgen/util.py
tests/generator/test_make_train.py

add an option to merge data to one H5 file

---

dpgen/generator/run.py

If the user writes a wrong path in "sys_configs", this warning can help locate the problem.

Raise warnings if there is no system in the path listed in sys_configs

---

dpgen/generator/run.py

Added the `model_devi_merge_traj` parameter to allow the merging of trajectories into one file using the lmp_input template.

Updated the `revise_lmp_input_dump` function.

---

dpgen/auto_test/reproduce.py

previous natoms only count #atom of the first element, gives wrong results or -inf in multiple-element cases

bug_fix reproduce.py

---

dpgen/util.py
tests/generator/test_make_train.py

In this method, `p2` has been started with `/` so no `/` should be added again.

fix a bug in `convert_training_data_to_hdf5`

---

dpgen/generator/arginfo.py
dpgen/generator/run.py

add dp_train_skip_neighbor_stat argument

---

dpgen/generator/arginfo.py
dpgen/generator/run.py

This allows setting batches of mixed systems, i.e. `mixed:N`, without being overridden by DP-GEN.
P.S. now `mixed:N` does work in my systems.

support `mixed:N` batch size

---

dpgen/generator/run.py

#803 changed the behavior of sys_idx in the fp step and caused there to be lots of systems. However, it failed to try to get the batch size of these systems.

fix batch size for simplify

---

dpgen/auto_test/lib/abacus.py

Original function `poscar2stru()` use dpdata.System to read POSCAR, but it will rotate the structure to make cell to be lower triangular, and this rotation is unexpected.

refactor(abacus): modify poscar2stru in auto_test.lib.abacus

---

dpgen/simplify/simplify.py

which does not come from `pick_data`

simplify: allow initial models trained by initial data

---

dpgen/simplify/simplify.py

If there is no candidate (i.e. all accurate or all failed), `picked_data_path` will not be dumped.

simplify: do not symlink if the file does not exist

---

dpgen/simplify/simplify.py

`System.append` is slow as it concatenates arrays. Thus, this PR reduces the times of `System.append`.

simplify: improve performance of selecting frames

---

dpgen/generator/run.py
dpgen/simplify/arginfo.py
dpgen/simplify/simplify.py
tests/generator/test_gromacs_engine.py

Fix #1222.
Currently, `make_fp` does two things: (1) select candidates from the model_devi task; (2) make FP input file. They are in the same method. This commit splits the method into two independent methods, `make_fp_configs` and `make_fp_calculation`. Run and simplify have their own `make_fp_configs`, but share the same `make_fp_calculation`.
The existing problem is that `make_fp_configs` generates different formats for different model_devi_engine. (e.g., POSCAR for lammps) We should resolve this problem in the future.

split make_fp and share `make_fp_calculation` between run and simplify

---

dpgen/generator/arginfo.py
dpgen/generator/run.py
dpgen/simplify/arginfo.py
dpgen/util.py
tests/generator/context.py
tests/generator/param-custom-fp.json
tests/generator/test_make_fp.py
tests/generator/test_post_fp.py

Add fp_style custom. One can use customized codes to run FP tasks and is not limited to what DP-GEN supports.

add fp_style custom

---

dpgen/data/tools/create_random_disturb.py
dpgen/data/tools/io_lammps.py

```
/opt/hostedtoolcache/Python/3.9.17/x64/lib/python3.9/site-packages/ase/atoms.py:967: VisibleDeprecationWarning: Use get_global_number_of_atoms() instead
```

Use get_global_number_of_atoms() instead

---

dpgen/generator/arginfo.py

The current documentation needs to be corrected. See also #596.

docs: fix docs for fp_task_min

---

dpgen/arginfo.py
dpgen/generator/arginfo.py
pyproject.toml

Considering one may write these arguments as 1D lists.

check arguments with 2D lists

---

dpgen/util.py

throw RuntimeError if no system is found by expand_sys_str

---

dpgen/simplify/arginfo.py
dpgen/simplify/simplify.py
tests/simplify/test_post_model_devi.py
tests/simplify/test_run_model_devi.py

i.e. Eq. B.2 in the DP-GEN paper.
Requires DeePMD-kit version >=2.2.4.

simplify: support using true error as error indicator

---

dpgen/generator/arginfo.py
dpgen/generator/run.py
tests/generator/param-amber.json
tests/generator/test_make_md.py

Add the `restart_from_iter` option in each iteration of DPRc simulations to restart from a previous iteration instead of initial structures.

dprc: add `restart_from_iter` option

---

dpgen/generator/run.py
dpgen/simplify/simplify.py
dpgen/util.py
pyproject.toml
tests/generator/context.py
tests/generator/test_post_fp.py

support electronic tempeture data used in simplify; refactor post_fp_vasp

---

dpgen/simplify/simplify.py

`dp model-devi` appends output into the existing file instead of overwriting it, so if there is an existing file (maybe caused by restart), there might be errors in reading it.
`rm -f` does not check if the file exists and always returns exit code 0.

rm old files when performing `dp model-devi`

---

dpgen/generator/arginfo.py
dpgen/generator/run.py
tests/generator/test_make_train.py

support training with -f or -t argument

---

dpgen/data/reaction.py

Fix #1351.
The old code seems to be wrong. Since the old dispatcher has been entirely removed, the code can be more simple.

fix KeyError in init_reaction

---

README.md
doc/overview/overview.md

Since the dpgen conda package on the deepmodeling channel and the offline packages are not maintained anymore, this PR removes the related documentation.

docs: update installation documentation

---

.pre-commit-config.yaml
dpgen/auto_test/lib/lammps.py
dpgen/generator/lib/abacus_scf.py
dpgen/generator/lib/calypso_run_opt.py
dpgen/generator/run.py
dpgen/tools/auto_gen_param.py
dpgen/tools/stat_iter.py
dpgen/tools/stat_time.py
pyproject.toml

See https://astral.sh/blog/the-ruff-formatter.

move to ruff formatter

---

MANIFEST.in

According to https://pypi.org/project/dpgen/0.12.0/#files, these files are too large.

exclude docs and tests from sdist

---

dpgen/generator/run.py

throw error if training_iter0_model_path is not found

---

dpgen/generator/run.py

Single quotes (`'`) can be automatically escaped. One does not need to escape single quotes in `command` manually anymore.
To those who have escaped single quotes in `command` manually, this is a breaking change.

breaking: use `shlex.quote` to quote shell commands

---

dpgen/simplify/arginfo.py

add document for pwscf in dpgen simplify

dpgen simplify: add document for fp style pwscf

---

dpgen/data/surf.py
dpgen/data/tools/bcc.py
dpgen/data/tools/diamond.py
dpgen/data/tools/fcc.py
dpgen/data/tools/hcp.py
dpgen/data/tools/sc.py
tests/generator/test_make_fp.py

There are 2 changes in pymatgen which destroy the previous unittests:
1. https://github.com/materialsproject/pymatgen/pull/3542
Previously we set the type of DummySpecies to "Type", which is forbidden by pymatgen through this PR. Here we replace "Type" with "X".
2. https://github.com/materialsproject/pymatgen/pull/3561
The functions from_string and get_string have been replaced with from_str and get_str. We should keep up to date with these changes.

Fix UTs destroyed by pymatgen's update

---

dpgen/generator/run.py

The previous implementation of deleting model_devi.out files after they are concatenated to a single file is not a good practice. It does not allow one to keep track of the behaviors of each bead. This PR keeps the original model_devi.out files for pimd.

keep original model_devi.out files for pimd

---

.mailmap

Fix my name at https://docs.deepmodeling.com/projects/dpgen/en/latest/credits.html. An incorrect name, "Jinzh Zeng", was used in a commit.
See https://git-scm.com/docs/gitmailmap for the principle.
I didn't fix other people's names, but they can do the same thing as this PR.

docs: fix author name

---

dpgen/generator/run.py
pyproject.toml
tests/generator/test_post_fp.py

Modify the post_fp_cp2k function to generate multisystem data. Allows to run different system at one single iteration model_devi step.

Modify the post_fp_cp2k function to generate multisystem data. Allows to run different system at one single iteration model_devi step.
