- README.md
- auto_test/lib/RemoteJob.py
- auto_test/lib/utils.py
- auto_test/param.json
- auto_test/run.py
Update:
dpgen manual (auto_test part)
Non-critical Changes:
add the information of configurations in the record format (**lib/utils.py**)
Critical Changes:
fix the task logical bug about detemine statement in run_task() in **run.py**
fix the path typo in run_interstitial() in **run.py**
> Update manual and fix the logical bug

- dpgen/auto_test/gen_01_eos.py
- dpgen/auto_test/gen_02_elastic.py
- dpgen/auto_test/gen_03_vacancy.py
- dpgen/auto_test/gen_04_interstitial.py
- dpgen/auto_test/gen_05_surf.py
- dpgen/auto_test/run.py
- dpgen/remote/group_jobs.py
define lammps.in and *.pb as common_files
upload softlink of common_files in each task folder
> Devel Update :Improved redundancy of uploaded *.pb files

- generator/lib/RemoteJob.py
Gaussian will return a non-zero exit code if the job does not reach convergence. This option will allow the script to continue to run even if a command fails.
> add an option to allow job to fail

- generator/lib/RemoteJob.py
- generator/run.py
- 支持LSF调度系统（已测试）
- 修复昨天#17 创造的bug（generator/lib/RemoteJob.py#L397, #L521）
- 修复一个远古typo （generator/lib/RemoteJob.py#L12）
> add LSF support and bugfix

- generator/lib/gaussian.py
> bugfix for #20

- dpgen/auto_test/cmpt_06_phonon.py
- dpgen/auto_test/cmpt_07_SScurve.py
- dpgen/auto_test/cmpt_08_dislocation.py
- dpgen/auto_test/gen_00_equi.py
- dpgen/auto_test/gen_01_eos.py
- dpgen/auto_test/gen_02_elastic.py
- dpgen/auto_test/gen_03_vacancy.py
- dpgen/auto_test/gen_04_interstitial.py
- dpgen/auto_test/gen_05_surf.py
- dpgen/auto_test/gen_06_phonon.py
- dpgen/auto_test/gen_07_SScurve.py
- dpgen/auto_test/gen_08_dislocation.py
- dpgen/auto_test/lib/lammps.py
- dpgen/auto_test/lib/vasp.py
- dpgen/auto_test/run.py
- examples/auto_test/param.json
new feature (still testing): 
Stress-Strain curve
dislocation
Using new structure to represent lammps model and parameter，which removed the redundancy between deepmd and meam.
Besides, it provide an simple way to add new package of lammps such as **eam** in future.
> Add new test features and removed the  redundancy between deepmd and meam

- dpgen/auto_test/gen_01_eos.py
- dpgen/auto_test/gen_06_phonon.py
- dpgen/auto_test/run.py
- examples/auto_test/param.json
- setup.py
Temporarily hide the permission of parameter setting (fix_volume option) in gen_01_eos.py
update install_requires in setup.py
> Update install requires

- dpgen/auto_test/cmpt_04_interstitial.py
- dpgen/auto_test/gen_04_interstitial.py
- dpgen/auto_test/run.py
fix the path bug about reproducing trajectories
> Fix a critical bug about reproducing trajectories in task **interstitial** 

- dpgen/generator/run.py
This version can run the full CH4 example using cp2k_fp
> fix bug for cp2k

- dpgen/generator/run.py
- setup.py
follows deepmodeling/dpdata#37
> assign type_map when calling dpdata

- dpgen/generator/run.py
> skip check_type_map for empty system

- setup.py
```python
python_requires="~=3.6",
```
Raise an ERROR for python<3.6
> add python_requires in setup.py

- examples/run/dp-lammps-siesta/dp-lammps-siesta/CH4/param_CH4.json
- examples/run/dp-lammps-siesta/dp-lammps-siesta/CH4/param_CH4.yaml
> ADD siesta_example

- dpgen/generator/run.py
> add an option to skip write out files (fix #109)

- dpgen/dispatcher/AWS.py
- dpgen/dispatcher/Dispatcher.py
> new class AWS

- dpgen/dispatcher/AWS.py
> AWS support restrat

- dpgen/dispatcher/AWS.py
> AWS bug fix

- examples/machine/machine-lsf.json
Add an example `machine.json` for LSF job management system, which has been tested to work well with real HPC.
> Add an example machine.json for LSF system

- dpgen/generator/lib/gaussian.py
Drop atoms that are out of the hard cutoff anyway even if the bond is cut.
And add comments and fix bugs.
> add a "hard cutoff" for clusters

- .travis.yml
- setup.py
update the requirement for pymatgen.
> unittest with python 3.7. 

- dpgen/generator/run.py
> support nopbc

- dpgen/generator/run.py
thanks to Manyi Yang, who came up with this idea three months ago...
> restart training if interrupted

- dpgen/dispatcher/Slurm.py
> should be nj>=task_max, not nj<task_max

- dpgen/dispatcher/SSHContext.py
- dpgen/dispatcher/Slurm.py
In my experience, sometimes dpgen fails to execute slurm commands. In this commit, dpgen will sleep 60 s and retry for at most 3 times.
> retry slurm commands when failing

- dpgen/auto_test/run.py
- dpgen/dispatcher/ALI.py
- dpgen/dispatcher/Dispatcher.py
- dpgen/dispatcher/DispatcherList.py
1.change job_record.context structure from list to dict. 
- local_root
- remote_root
- job_uuid
- ip
- instance_id
2.add DispatcherList.py, can derivate to other cloud platform
3.change run_tasks in autotest/run.py, send all_task to ALI
4.surport manual_create, manual_delete
5.change machine-ali.json:
- add cloud_resources for ali, which are unique parts for ali and other cloud platform
- use machine_upper_bound to constraint machine number
> pr ALI.py DispatcherList.py

- dpgen/__init__.py
working around the issue of `pymatgen.__version__`
> stop printing the dependencies

- dpgen/dispatcher/Slurm.py
> support add Slurm custom flags

- dpgen/dispatcher/SSHContext.py
If the number of files is too much, it will raise an error
"Argument list too long". A solution is to split it to several
commands.
> RuntimeError: Get error code 1 in calling tar czf ...  through ssh with job: 57c454d1-1ca2-4b6b-a5c4-8c468898586e . message: /bin/bash: Argument list too long
> fix "Argument list too long" for tar command

- dpgen/dispatcher/SSHContext.py
> fix SSH session not active

- dpgen/dispatcher/PBS.py
fix the bug posted on:
https://github.com/deepmodeling/dpgen/issues/395
> add another check_status option for psate (PBS)

- dpgen/auto_test/Lammps.py
Typo in auto_test/Lammps.pu
The bug is reported here:
https://gitee.com/deepmodeling/deepmd-kit/issues/I3T98B
> Fixed a bug in dpgen/auto_test/Lammps.py

- dpgen/generator/run.py
OK, this is a small change. But it really took me a while to find what the problem is with the old error message.
> Changed the error log of too many failed frames

- dpgen/generator/run.py
This PR is aimmed to support DeePMD-kit 2. Fix #386.
support deepmd 2.0
- support dp 2.0
- support dp 2.0
- support dp 2 auto_prob
> support DeePMD-kit 2

- examples/machine/DeePMD-kit-1.x/machine-lsf-slurm-cp2k.json
- examples/run/dp1.x-lammps-cp2k/methane/param-ch4.json
- examples/run/dp1.x-lammps-cp2k/methane/template.inp
commit for this request
https://github.com/deepmodeling/dpgen/issues/450
> Update CP2K new example and slurm-lsf-mix machine

- dpgen/generator/run.py
> support hybrid descriptor (fix #458)

- CITATION.cff
[GitHub just supported this feature](https://github.blog/2021-08-19-enhanced-support-citations-github/).
Preview in [my fork](https://github.com/njzjz/dpgen):
> add CITATION.cff to show citation in GitHub

- dpgen/remote/decide_machine.py
cant get group_size in older ALI-Dispatcher
> modify decide_machine for older ALI-Dispatcher

- .github/workflows/release.yml
fix typo in github actions release to conda
> fix typo in github actions release to conda

- dpgen/dispatcher/SSHContext.py
> ssh: archieve files the symlink points to instead of symlink iteself 

- dpgen/auto_test/EOS.py
bug introduced by pr #611
list.sum() --> sum(list)
> bug_fix | previous patch crashed

- dpgen/simplify/simplify.py
Update simplify.py, modified run_model_devi() for api > 1.0 , and modified  make_model_devi() and post_model_devi() to fix multi-suffixes bug .
> Update simplify.py for api > 1.0, and fix multi-suffixes bug .

- dpgen/generator/run.py
(cherry picked from commit 1f1a39c8a543f5923cb911622c7f6af612a74d34)
> set the seed of type_embedding network

- README.md
- dpgen/generator/lib/abacus_scf.py
Avoid turning "k_points" value in user_fp_params to parameter in INPUT file.
> fix a bug in make_abacus_scf_input

- dpgen/generator/arginfo.py
(cherry picked from commit f5782ea2b33c3ee638ab23bc0e1e4a19b8d578e3)
> args: `model_devi_v_trust_lo` and `model_devi_v_trust_hi` are optional

- dpgen/generator/run.py
- tests/generator/test_make_md.py
> fix UT test_make_md

- README.md
#476 The type of `fp_aniso_kspacing` should be `List of float`
> Update the type of `fp_aniso_kspacing` as `List of float`

- dpgen/generator/run.py
`run_tasks` for `model_devi` step should not be empty. see #333 
a warning will be given when `run_tasks` is abnormal
> Check run_tasks before submission in run_md_model_devi

- setup.py
> add dargs to install_requires

- tests/data/test_disturb_abacus.py
Check the minimum distance between atoms after perturbation of structure.
> UT: update test_disturb_abacus.py

- doc/index.rst
- doc/init/init_surf.md
describe the init_surf and show an example about the init_surf by /doc/init/init_surf.md . Then, add the link of init_surf.md into the /doc/index.rst
> Goodluck xyz patch add init surf

- dpgen/generator/arginfo.py
- examples/run/deprecated/dp1.x-gromacs-gaussian/param.json
- examples/run/dp2.x-gromacs-gaussian/param.json
- examples/run/dprc/generator.json
- examples/run/dprc/generator.yaml
- tests/test_check_examples.py
> add DPRc (model_devi_engine `amber` and fp_style `amber/diff`) arguments

- dpgen/generator/run.py
Reverts deepmodeling/dpgen#944
> Revert "fix: remove lmp_traj from forward_files in run_md_model_devi"

- pyproject.toml
> bump requires-python to `>=3.8`

- dpgen/generator/lib/run_calypso.py
- dpgen/generator/run.py
- dpgen/simplify/simplify.py
- tests/generator/test_post_fp.py
> assign type_map for all systems

- .github/workflows/test.yml
same as https://github.com/deepmodeling/deepmd-kit/pull/2141
> add pass step to GitHub Actions

- dpgen/data/gen.py
Fix #1108.
Note: tests do not cover this case.
> fix compatibility with the latest pymatgen

- .pre-commit-config.yaml
- dpgen/auto_test/Property.py
- dpgen/auto_test/Task.py
> fix numpydoc styles

- .github/workflows/test.yml
The old version is broken again.
> bump pymatgen to 2023.5.31

- .github/workflows/release.yml
> use OIDC to publish packages

- .github/workflows/test.yml
> test: pin pymatgen-analysis-defects to <2023.08.22

- doc/requirements.txt
See https://github.com/sphinx-doc/sphinx/issues/11662. I hope it can be fixed in the next Sphinx version.
> skip Sphinx 7.2.5

- dpgen/generator/arginfo.py
> docs: add links to external documentation

- dpgen/generator/lib/pwscf.py
write floating point number for atomic masses in QE input files
> pwscf: write floaing point number for atomic masses

- dpgen/generator/run.py
- tests/generator/test_make_md.py
put LAMMPS's log files in backward_files for pimd
> model devi: download LAMMPS log files for pimd

- dpgen/generator/run.py
- dpgen/simplify/simplify.py
The current behavior is that all previous iterations are logged.
> only log the current iteration when restarting

- dpgen/data/gen.py
> Fix exception message
